baseURL = "https://jonatansolheim.no/"
author = "Jonatan Solheim"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "Jonatan Solheim"

[params]
color = 'linen'

github = 'jonatso'
linkedin = 'solheimjonatan'

name = "Hi, I'm Jonatan!"
bio = "I'm currently studying Computer Science at NTNU, planning to finishing my masters degree in 2025. Interested in web development, computer architecture, music production and rubik's cubes. On this page, you will find information about my projects, music and cubing."
avatar = 'tilingen@gmail.com'

monoDarkIcon = true # show monochrome dark mode icon

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]
# menus = [
#     { identifier = "programming", name = "Programming", url = "/programming/", weight = 10 },
#     { identifier = "cubing", name = "Cubing", url = "/cubing/", weight = 10 },
#     { identifier = "music", name = "Music", url = "/music/", weight = 10 },
# ]

[[menu.main]]
identifier = "programming"
name = "Programming"
url = "/programming/"
weight = 10
[[menu.main]]
identifier = "cubing"
name = "Cubing"
url = "/cubing/"
weight = 20
[[menu.main]]
identifier = "music"
name = "Music"
url = "/music/"
weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
